export const teamMembersList = [
  {
    id: 1,
    thumbnail: "",
    name: "Sude Filikçi",
    position: "Devops",
    progress: 40,
    color: "#ea4d4d",
  },

  {
    id: 2,
    thumbnail: "",
    name: "Ayşegül Altıntaş",
    position: "Kullanıcı Arayüzü / Deneyimi Tasarımcısı",
    progress: 65,
    color: "#3454d1",
  },
  {
    id: 3,
    thumbnail: "",
    name: "Esmanur Erden",
    position: "Devops",
    progress: 50,
    color: "#ffa21d",
  },
  {
    id: 4,
    thumbnail: "",
    name: "Aleynagül Kazdal",
    position: "UI/UX DESIGNER",
    progress: 75,
    color: "#17c666",
  },
  {
    id: 5,
    thumbnail: "",
    name: "Zeynep Daş",
    position: "Tam Donanımlı Geliştirici",
    progress: 75,
    color: "#17c666",
  },
  {
    id: 6,
    thumbnail: "",
    name: "Sümeyye Bire",
    position: "Tam Donanımlı Geliştirici",
    progress: 75,
    color: "#17c666",
  },
];
